const fs = require('fs');
const path = require('path');

// Danh sách toàn bộ các file cần tạo dựa theo cấu trúc của bạn
const files = [
  "src/app/(auth)/layout.tsx",
  "src/app/(auth)/login/page.tsx",
  "src/app/(auth)/register/page.tsx",
  "src/app/(admin)/layout.tsx",
  "src/app/(admin)/middleware-check.tsx",
  "src/app/(admin)/overview/page.tsx",
  "src/app/(admin)/products/page.tsx",
  "src/app/(admin)/products/[id]/page.tsx",
  "src/app/(admin)/suppliers/page.tsx",
  "src/app/(admin)/suppliers/[id]/page.tsx",
  "src/app/(admin)/orders/page.tsx",
  "src/app/(admin)/orders/[id]/page.tsx",
  "src/app/(admin)/customers/page.tsx",
  "src/app/(admin)/customers/[id]/page.tsx",
  "src/app/(admin)/categories/page.tsx",
  "src/app/(admin)/analytics/page.tsx",
  "src/app/(admin)/payments/page.tsx",
  "src/app/(admin)/content/page.tsx",
  "src/app/(admin)/settings/page.tsx",
  "src/app/(store)/layout.tsx",
  "src/app/(store)/page.tsx",
  "src/app/(store)/products/page.tsx",
  "src/app/(store)/products/[slug]/page.tsx",
  "src/app/(store)/categories/[slug]/page.tsx",
  "src/app/(store)/cart/page.tsx",
  "src/app/(store)/checkout/page.tsx",
  "src/app/(store)/search/page.tsx",
  "src/app/(store)/account/layout.tsx",
  "src/app/(store)/account/profile/page.tsx",
  "src/app/(store)/account/orders/page.tsx",
  "src/app/(store)/account/orders/[id]/page.tsx",
  "src/app/(store)/account/addresses/page.tsx",
  "src/api/auth/[...nextauth]/route.ts",
  "src/api/admin/products/route.ts",
  "src/api/admin/products/[id]/route.ts",
  "src/api/admin/suppliers/route.ts",
  "src/api/admin/suppliers/[id]/route.ts",
  "src/api/admin/orders/route.ts",
  "src/api/admin/orders/[id]/route.ts",
  "src/api/admin/customers/route.ts",
  "src/api/admin/customers/[id]/route.ts",
  "src/api/admin/categories/route.ts",
  "src/api/admin/categories/[id]/route.ts",
  "src/api/admin/analytics/route.ts",
  "src/api/admin/payments/route.ts",
  "src/api/admin/payments/refunds/route.ts",
  "src/api/admin/content/route.ts",
  "src/api/store/products/route.ts",
  "src/api/store/products/[slug]/route.ts",
  "src/api/store/categories/route.ts",
  "src/api/store/cart/route.ts",
  "src/api/store/orders/route.ts",
  "src/api/store/orders/[id]/route.ts",
  "src/api/store/account/profile/route.ts",
  "src/api/store/account/addresses/route.ts",
  "src/api/store/search/route.ts",
  "src/api/store/chatbot/route.ts",
  "src/components/ui/Button.tsx",
  "src/components/ui/Input.tsx",
  "src/components/ui/Badge.tsx",
  "src/components/ui/Card.tsx",
  "src/components/ui/Modal.tsx",
  "src/components/ui/Table.tsx",
  "src/components/ui/Pagination.tsx",
  "src/components/ui/Select.tsx",
  "src/components/ui/Toggle.tsx",
  "src/components/ui/index.ts",
  "src/components/admin/layout/AdminSidebar.tsx",
  "src/components/admin/layout/AdminTopbar.tsx",
  "src/components/admin/layout/AdminShell.tsx",
  "src/components/admin/charts/RevenueLineChart.tsx",
  "src/components/admin/charts/OrderStatusDonut.tsx",
  "src/components/admin/charts/TopProductsBar.tsx",
  "src/components/admin/charts/CategoryRevenueBar.tsx",
  "src/components/admin/overview/KpiCards.tsx",
  "src/components/admin/overview/RecentOrdersList.tsx",
  "src/components/admin/overview/LowStockTable.tsx",
  "src/components/admin/overview/ActivityFeed.tsx",
  "src/components/admin/products/ProductTable.tsx",
  "src/components/admin/products/ProductFilter.tsx",
  "src/components/admin/products/ProductFormModal.tsx",
  "src/components/admin/suppliers/SupplierGrid.tsx",
  "src/components/admin/suppliers/SupplierCard.tsx",
  "src/components/admin/suppliers/SupplierDetailPanel.tsx",
  "src/components/admin/orders/OrderTable.tsx",
  "src/components/admin/orders/OrderStatusTabs.tsx",
  "src/components/admin/orders/OrderDetailModal.tsx",
  "src/components/admin/customers/CustomerTable.tsx",
  "src/components/admin/customers/CustomerSidePanel.tsx",
  "src/components/admin/settings/StoreInfoForm.tsx",
  "src/components/admin/settings/ChatbotConfigForm.tsx",
  "src/components/admin/settings/PermissionsTable.tsx",
  "src/components/store/layout/StoreHeader.tsx",
  "src/components/store/layout/StoreFooter.tsx",
  "src/components/store/layout/StoreShell.tsx",
  "src/components/store/home/HeroBanner.tsx",
  "src/components/store/home/FeaturedProducts.tsx",
  "src/components/store/home/CategoryGrid.tsx",
  "src/components/store/products/ProductCard.tsx",
  "src/components/store/products/ProductGrid.tsx",
  "src/components/store/products/ProductFilter.tsx",
  "src/components/store/products/ProductDetail.tsx",
  "src/components/store/products/RelatedProducts.tsx",
  "src/components/store/cart/CartDrawer.tsx",
  "src/components/store/cart/CartItem.tsx",
  "src/components/store/cart/CartSummary.tsx",
  "src/components/store/checkout/CheckoutForm.tsx",
  "src/components/store/checkout/OrderSummary.tsx",
  "src/components/store/account/ProfileForm.tsx",
  "src/components/store/account/OrderHistoryList.tsx",
  "src/components/store/account/AddressManager.tsx",
  "src/components/store/chatbot/ChatbotButton.tsx",
  "src/components/store/chatbot/ChatbotDrawer.tsx",
  "src/components/shared/PageHeader.tsx",
  "src/components/shared/EmptyState.tsx",
  "src/components/shared/LoadingSkeleton.tsx",
  "src/components/shared/ConfirmDialog.tsx",
  "src/hooks/admin/useAdminProducts.ts",
  "src/hooks/admin/useAdminOrders.ts",
  "src/hooks/admin/useAdminSuppliers.ts",
  "src/hooks/admin/useAdminCustomers.ts",
  "src/hooks/admin/useAnalytics.ts",
  "src/hooks/store/useProducts.ts",
  "src/hooks/store/useCart.ts",
  "src/hooks/store/useOrders.ts",
  "src/hooks/store/useChatbot.ts",
  "src/hooks/store/useSearch.ts",
  "src/hooks/shared/useDebounce.ts",
  "src/hooks/shared/useLocalStorage.ts",
  "src/services/admin/product.service.ts",
  "src/services/admin/supplier.service.ts",
  "src/services/admin/order.service.ts",
  "src/services/admin/customer.service.ts",
  "src/services/admin/analytics.service.ts",
  "src/services/admin/payment.service.ts",
  "src/services/store/product.service.ts",
  "src/services/store/cart.service.ts",
  "src/services/store/order.service.ts",
  "src/services/store/account.service.ts",
  "src/services/store/chatbot.service.ts",
  "src/lib/prisma.ts",
  "src/lib/auth.ts",
  "src/lib/api-response.ts",
  "src/lib/format.ts",
  "src/lib/constants.ts",
  "src/lib/utils.ts",
  "src/schemas/product.schema.ts",
  "src/schemas/supplier.schema.ts",
  "src/schemas/order.schema.ts",
  "src/schemas/customer.schema.ts",
  "src/schemas/category.schema.ts",
  "src/schemas/auth.schema.ts",
  "src/schemas/index.ts",
  "src/types/api.types.ts",
  "src/types/auth.types.ts",
  "src/types/index.ts",
  "src/middleware.ts"
];

files.forEach(filePath => {
  // Đường dẫn tuyệt đối
  const absolutePath = path.join(__dirname, filePath);
  
  // Lấy thư mục chứa file
  const dir = path.dirname(absolutePath);

  // Tạo thư mục nếu chưa có (recursive: true giúp tạo cả thư mục cha)
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  // Tạo file rỗng nếu chưa có
  if (!fs.existsSync(absolutePath)) {
    fs.writeFileSync(absolutePath, '');
    console.log(`✅ Created: ${filePath}`);
  } else {
    console.log(`⏩ Skipped (already exists): ${filePath}`);
  }
});

console.log('🎉 Done! Đã setup xong cấu trúc thư mục.');